---
- include_vars: password.yml

- name: libncurses5-dev
  apt:
    name: libncurses5-dev
    state: latest
  register: installation
  become: yes

- name: Cloning  imgcat_repo
  git:
    repo=https://github.com/eddieantonio/imgcat.git
    dest=/tmp/imgcat
  register: cloning
  become: no

- block:
  - name: autoconf
    command: autoconf
    args:
      chdir: /tmp/imgcat/

  - name: configure
    command: ./configure
    args:
      chdir: /tmp/imgcat/

  - name: make
    command: make
    args:
      chdir: /tmp/imgcat/

  - name: install
    command: make install
    args:
      chdir: /tmp/imgcat/
    become: yes
  when: cloning.changed