---
- include_vars: password.yml

- name: Installing autotools, make and libncurses5-dev
  apt: pkg=libncurses5-dev,autoconf,make state=latest
  register: installation
  become: yes

- name: Cloning  imgcat_repo
  git:
    repo=https://github.com/eddieantonio/imgcat.git
    dest=/tmp/imgcat
  register: cloning
  become: no

- name: autoconf
  command: autoconf
  args:
    chdir: /tmp/imgcat/
  when: cloning.changed
  register: autoconf

- name: configure
  command: ./configure
  args:
    chdir: /tmp/imgcat/
  when: autoconf.changed
  register: configure

- name: make
  command: make
  args:
    chdir: /tmp/imgcat/
  when: configure.changed
  register: make

- name: install
  command: make install
  args:
    chdir: /tmp/imgcat/
  become: yes
  when: make.changed